const sectionToQuartier = {
    'BU': 'Trivaux-la Garenne',
    'O': 'Gare',
    'AF': 'Centre',
    'N': 'Gare',
    'G': 'Gare',
    'F': 'Gare',
    'BO': 'Trivaux-la Garenne',
    'B': 'Percy-Schneider',
    'C': 'Percy-Schneider',
    'AB': 'Centre',
    'K': 'Gare',
    'Z': 'Percy-Schneider',
    'A': 'Percy-Schneider',
    'AI': 'Galvents-Corby',
    'V': 'Percy-Schneider',
    'BF': 'Jardin Parisien',
    'Q': 'Gare',
    'AZ': 'Jardin Parisien',
    'BC': 'Jardin Parisien',
    'BP': 'Trivaux-la Garenne',
    'AJ': 'Galvents-Corby',
    'AQ': 'Galvents-Corby',
    'E': 'Gare',
    'AM': 'Centre',
    'Y': 'Percy-Schneider',
    'D': 'Gare',
    'R': 'Gare',
    'M': 'Gare',
    'L': 'Gare',
    'AN': 'Galvents-Corby',
    'AE': 'Centre',
    'T': 'Gare',
    'S': 'Gare',
    'BE': 'Jardin Parisien',
    'BQ': 'Trivaux-la Garenne',
    'BX': 'Trivaux-la Garenne',
    'BH': 'Plaine',
    'U': 'Gare',
    'BS': 'Trivaux-la Garenne',
    'AC': 'Centre',
    'BL': 'Plaine',
    'BK': 'Plaine',
    'BJ': 'Plaine',
    'BM': 'Trivaux-la Garenne',
    'AG': 'Galvents-Corby',
    'AY': 'Jardin Parisien',
    'H': 'Gare',
    'AD': 'Centre',
    'BT': 'Trivaux-la Garenne',
    'J': 'Gare',
    'AH': 'Galvents-Corby',
    'AR': 'Galvents-Corby',
    'AL': 'Centre',
    'X': 'Percy-Schneider',
    'AK': 'Centre',
    'BD': 'Jardin Parisien',
    'BR': 'Trivaux-la Garenne',
    'AS': 'Centre',
    'BG': 'Jardin Parisien',
    'BV': 'Trivaux-la Garenne',
    'BN': 'Trivaux-la Garenne',
    'AO': 'Galvents-Corby',
    'AP': 'Galvents-Corby',
    'AT': 'Centre',
    'AU': 'Percy-Schneider',
    'P': 'Gare',
    'AV': 'Percy-Schneider',
    'BI': 'Plaine',
    'I': 'Gare'
}

module.exports = { sectionToQuartier };